### PR TITLE
Null Safety support for Jaguar JWT

### PR DESCRIPTION
**Pull request by VB10**

### CODE REVIEW

**Comment by debkanchan** [comment]
`dart migrate` shows there's a lot to be done.

also only crypto is null safe. This is essentially blocked unless the dependencies migrate to null safety

**Comment by VB10** [comment]
yes you right, I update dependency for my project fastly so now complete migration, it will be supported now

**Comment by debkanchan** [comment]
+1 bump for review

**Comment by debkanchan** [comment]
@hoylen @tejainece @Kleak

**Comment by tejainece** [comment]
Thanks for the PR. I will review it and merge it today or tomorrow.

**Comment by hoylen** [comment]
Looks good. I can't easily test if the crypto still produces the correct results, but I've found this breaking change.

**Incorrect cast**

Previously, you could create a `JwtClaim` where the `otherClaims` contains _null_ values for a map inside that map. For example,

```
JwtClaim(
  subject: ...
  issuer: ...
  ...
  otherClaims: <String, Object?>{
    'typ': 'authnresponse',
    'myCustomMember': <String,Object?>{
      'foo': 42,
      'bar': null, // this no longer works: runtime error
    }
  }
);
```
And the JSON inside the JWT token will be:

```
{
  "iss": ...
  "sub": ...
  ...
  "typ": "authnresponse",
  "myCustomMember": {
    "foo": 42,
    "bar": null
  }
}
```

Since it can contain any valid JSON object, null is allowed as a member's value.

Currently, the above will crash because of an invalid cast, because while _otherClaims_ is a `Map<Object,Object?>` values of the members inside it cannot be.

Line 29 and 30 of _jaguar_jwt/lib/src/splay.dart_ makes an incorrect assumption in the casting:

```
  } else if (value is Map) {
    return _splayify(value as Map<Object, Object>);
```

If _value_ is a `Map` it could be a `Map<Object, Object?>` which cannot be cast to a `Map<Object, Object>`.

I think this can be fixed by defining `_splayify` to accept a `Map<Object,Object?>`, and avoid doing risky casting by using `if (value is Map<Object, Object?>) { return _splayify(value); ...`.

**Minor issues**

There are a few things the _Dart Analyser_ detected, such as redundant tests for null:

- lib/src/date.dart line 67
- lib/src/jaguar_jwt.dart line 114

There are also a few linter warnings that can be easily fixed up too.

**Comment by tejainece** [comment]
@VB10 Thanks for the PR. Unfortunately, I decided to port it to null safety myself. So I can also make some minor changes to API.

**Comment by tejainece** [comment]
The code ported to null safety is already merged into the git repository. Please check it out. There are some breaking changes. So I will refrain from publishing it to pub until you guys have had time to check it out and maybe find some issues.

**Comment by debkanchan** [comment]
@tejainece during your migration from `Object` to `dynamic` have you handled the cases where a non nullable `dynamic` variable can be null?

**Comment by tejainece** [comment]
I would suggest we move the discussions to the following thread: https://github.com/Jaguar-dart/session/issues/11

**Comment by tejainece** [comment]
@DebkanchanSamadder All values in the payload are nullable. If I missed it somewhere please create an issue. I will also write some testcases to test that null values are allowed.

**Comment by tejainece** [comment]
Published version 3.0.0 to pub with null safety support.

**Pull request closed without merging**
